/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class MalleyTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, MalleyTimeoutError.prototype);
    }
}
