/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Malley from "../../..";

export interface Movie {
    id: Malley.MovieId;
    title: string;
    /** The rating scale out of ten stars */
    rating: number;
}
