/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "./core";
import { Imdb } from "./api/resources/imdb/client/Client";

export declare namespace MalleyClient {
    interface Options {
        environment: core.Supplier<string>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class MalleyClient {
    constructor(protected readonly _options: MalleyClient.Options) {}

    protected _imdb: Imdb | undefined;

    public get imdb(): Imdb {
        return (this._imdb ??= new Imdb(this._options));
    }
}
